ping_stat_job:
  cron: "* * * * *"
  class: "PingStatJob"
  queue: default

automat_job:
  cron: "* * * * *"
  class: "AutomatJob"
  queue: default

smart_plug_state_job:
  cron: "* * * * *"
  class: "SmartPlugStateJob"
  queue: default

saved_energy_recompute_job:
  cron: "5 1 * * *"
  class: "SavedEnergyRecomputeJob"
  queue: default